### ISSUE TITLE
Unsure about output from flow_duration_curve

### ISSUE THREAD

**Issue by MarcusStrobl** [mmaelicke/hydrobox#2]
I would like to plot the output from `flow_duration_curve` in Bokeh, though the output seems not to be usable for that. 
According to the line for plotting in `flow_duration_curve` I should use sorted `x` and `p` values: 
```python
ax.plot(x[index], p[index], **kwargs)
```
sorted according to `p`:
```python
index = np.argsort(p)
```
The output of `flow_duration_curve` is `return p[index]`, but without the `index` I cannot create `x[index]`.
So I guess a better output would be `p` instead of `p[index]`, or a matching pair of `x[index]` and `p[index]`.

To illustrate the problem I added some images. The result plot of the tool looks like this:
![grafik](https://user-images.githubusercontent.com/20320927/80693156-e819ed80-8ad2-11ea-8da0-932215a7ccea.png)
Naive plot of result from `flow_duration_curve` with `x` looks like:
![grafik](https://user-images.githubusercontent.com/20320927/80693392-37601e00-8ad3-11ea-9336-c8852782a7bd.png)
Naive test to plot result from `flow_duration_curve` with `x[np.argsort(x)]` or `x[np.argsort(p)]` didn't work neither, of course.
![grafik](https://user-images.githubusercontent.com/20320927/80694123-57441180-8ad4-11ea-879f-23642f3c757f.png)
![grafik](https://user-images.githubusercontent.com/20320927/80694439-cf123c00-8ad4-11ea-9ef4-5a9069cbc125.png)

**Comment by mmaelicke** [comment]
Hey Marcus, 
The output of `flow_duration_curve(plot=False)` is just the sorted probabilities as you already stated. That means, if you just sort the *input*, the internal `index` is actually the same. Therefore, I think there is no need to return anything else, which would make the multidimensional case more complicated.

I don't have the real discharge data from the database here (so much VPN problems), but could verify with this short example:

```python
import numpy as np
from hydrobox import toolbox as tb
import matplotlib.pyplot as plt

data = np.random.gamma(150, 10, size=2000)

fig = tb.flow_duration_curve(data)
fig.show()

fig2, ax = plt.subplots(1,1)
ax.loglog()
p = tb.flow_duration_curve(data, plot=False)
data.sort()    # this is inplace, if you don't want to change data, use np.argsort to get the index
ax.plot(data, p)
```
produced the two graphs:
![image](https://user-images.githubusercontent.com/2826034/80700488-1bae4500-8ade-11ea-8630-83c811389fb8.png)

So I think sorting the *input* does the trick. Direction can be changed with the `non_exceeding` keyword.

Can you confirm?

**Comment by MarcusStrobl** [comment]
Hey Mirko,
thank you for your quick response. Not sure what I did wrong by trying to sort the column I extracted from my dataframe. Following your comments I sorted directly the output from `flow_duration_curve` with: `output.sort_values(by=['value'], ascending=False)` and it worked.
Sorry for the inconvenience and thank you for your help.
